/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type AssetStruct = {
  pool: PromiseOrValue<string>;
  manager: PromiseOrValue<string>;
  tokenId: PromiseOrValue<BigNumberish>;
  liquidity: PromiseOrValue<BigNumberish>;
  data: PromiseOrValue<BytesLike>;
};

export type AssetStructOutput = [
  string,
  string,
  BigNumber,
  BigNumber,
  string
] & {
  pool: string;
  manager: string;
  tokenId: BigNumber;
  liquidity: BigNumber;
  data: string;
};

export type ProvidedStruct = {
  tokens: PromiseOrValue<string>[];
  amounts: PromiseOrValue<BigNumberish>[];
  nfts: AssetStruct[];
};

export type ProvidedStructOutput = [
  string[],
  BigNumber[],
  AssetStructOutput[]
] & { tokens: string[]; amounts: BigNumber[]; nfts: AssetStructOutput[] };

export type DesiredStruct = {
  outputERC20s: PromiseOrValue<string>[];
  outputERC721s: AssetStruct[];
  ratios: PromiseOrValue<BigNumberish>[];
  minAmountsOut: PromiseOrValue<BigNumberish>[];
};

export type DesiredStructOutput = [
  string[],
  AssetStructOutput[],
  BigNumber[],
  BigNumber[]
] & {
  outputERC20s: string[];
  outputERC721s: AssetStructOutput[];
  ratios: BigNumber[];
  minAmountsOut: BigNumber[];
};

export type SwapPointStruct = {
  amountIn: PromiseOrValue<BigNumberish>;
  valueIn: PromiseOrValue<BigNumberish>;
  amountOut: PromiseOrValue<BigNumberish>;
  valueOut: PromiseOrValue<BigNumberish>;
  slippage: PromiseOrValue<BigNumberish>;
  tokenIn: PromiseOrValue<string>;
  swapper: PromiseOrValue<string>;
  tokenOut: PromiseOrValue<string>;
  path: PromiseOrValue<string>[];
};

export type SwapPointStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string,
  string,
  string[]
] & {
  amountIn: BigNumber;
  valueIn: BigNumber;
  amountOut: BigNumber;
  valueOut: BigNumber;
  slippage: BigNumber;
  tokenIn: string;
  swapper: string;
  tokenOut: string;
  path: string[];
};

export type ConversionStruct = {
  desiredERC721: AssetStruct;
  desiredERC20: PromiseOrValue<string>;
  value: PromiseOrValue<BigNumberish>;
  underlying: PromiseOrValue<string>[];
  underlyingValues: PromiseOrValue<BigNumberish>[];
};

export type ConversionStructOutput = [
  AssetStructOutput,
  string,
  BigNumber,
  string[],
  BigNumber[]
] & {
  desiredERC721: AssetStructOutput;
  desiredERC20: string;
  value: BigNumber;
  underlying: string[];
  underlyingValues: BigNumber[];
};

export interface UniversalSwapInterface extends utils.Interface {
  functions: {
    "estimateValue((address[],uint256[],(address,address,uint256,uint256,bytes)[]),address)": FunctionFragment;
    "estimateValueERC20(address,uint256,address)": FunctionFragment;
    "estimateValueERC721((address,address,uint256,uint256,bytes),address)": FunctionFragment;
    "getAmountsOut((address[],uint256[],(address,address,uint256,uint256,bytes)[]),(address[],(address,address,uint256,uint256,bytes)[],uint256[],uint256[]))": FunctionFragment;
    "getUnderlying(address[],uint256[])": FunctionFragment;
    "helper()": FunctionFragment;
    "isSupported(address)": FunctionFragment;
    "networkToken()": FunctionFragment;
    "owner()": FunctionFragment;
    "preSwapComputation((address[],uint256[],(address,address,uint256,uint256,bytes)[]),(address[],(address,address,uint256,uint256,bytes)[],uint256[],uint256[]))": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "stableToken()": FunctionFragment;
    "swap((address[],uint256[],(address,address,uint256,uint256,bytes)[]),(uint256,uint256,uint256,uint256,int256,address,address,address,address[])[],((address,address,uint256,uint256,bytes),address,uint256,address[],uint256[])[],(address[],(address,address,uint256,uint256,bytes)[],uint256[],uint256[]),address)": FunctionFragment;
    "swapAfterTransfer((address[],uint256[],(address,address,uint256,uint256,bytes)[]),(uint256,uint256,uint256,uint256,int256,address,address,address,address[])[],((address,address,uint256,uint256,bytes),address,uint256,address[],uint256[])[],(address[],(address,address,uint256,uint256,bytes)[],uint256[],uint256[]),address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "estimateValue"
      | "estimateValueERC20"
      | "estimateValueERC721"
      | "getAmountsOut"
      | "getUnderlying"
      | "helper"
      | "isSupported"
      | "networkToken"
      | "owner"
      | "preSwapComputation"
      | "renounceOwnership"
      | "stableToken"
      | "swap"
      | "swapAfterTransfer"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "estimateValue",
    values: [ProvidedStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateValueERC20",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateValueERC721",
    values: [AssetStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountsOut",
    values: [ProvidedStruct, DesiredStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnderlying",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(functionFragment: "helper", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isSupported",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "networkToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "preSwapComputation",
    values: [ProvidedStruct, DesiredStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stableToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      ProvidedStruct,
      SwapPointStruct[],
      ConversionStruct[],
      DesiredStruct,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAfterTransfer",
    values: [
      ProvidedStruct,
      SwapPointStruct[],
      ConversionStruct[],
      DesiredStruct,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "estimateValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateValueERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateValueERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountsOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "helper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "networkToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "preSwapComputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stableToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapAfterTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "AssetsSent(address,address[],address[],uint256[])": EventFragment;
    "NFTMinted(address,uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetsSent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTMinted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface AssetsSentEventObject {
  receiver: string;
  tokens: string[];
  managers: string[];
  amountsAndIds: BigNumber[];
}
export type AssetsSentEvent = TypedEvent<
  [string, string[], string[], BigNumber[]],
  AssetsSentEventObject
>;

export type AssetsSentEventFilter = TypedEventFilter<AssetsSentEvent>;

export interface NFTMintedEventObject {
  manager: string;
  tokenId: BigNumber;
  pool: string;
}
export type NFTMintedEvent = TypedEvent<
  [string, BigNumber, string],
  NFTMintedEventObject
>;

export type NFTMintedEventFilter = TypedEventFilter<NFTMintedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface UniversalSwap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniversalSwapInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    estimateValue(
      assets: ProvidedStruct,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    estimateValueERC20(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    estimateValueERC721(
      nft: AssetStruct,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAmountsOut(
      provided: ProvidedStruct,
      desired: DesiredStruct,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber[],
        SwapPointStructOutput[],
        ConversionStructOutput[],
        BigNumber[]
      ] & {
        amounts: BigNumber[];
        swaps: SwapPointStructOutput[];
        conversions: ConversionStructOutput[];
        expectedUSDValues: BigNumber[];
      }
    >;

    getUnderlying(
      tokens: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber[]]>;

    helper(overrides?: CallOverrides): Promise<[string]>;

    isSupported(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    networkToken(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    preSwapComputation(
      provided: ProvidedStruct,
      desired: DesiredStruct,
      overrides?: CallOverrides
    ): Promise<
      [SwapPointStructOutput[], ConversionStructOutput[]] & {
        swaps: SwapPointStructOutput[];
        conversions: ConversionStructOutput[];
      }
    >;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stableToken(overrides?: CallOverrides): Promise<[string]>;

    swap(
      provided: ProvidedStruct,
      swaps: SwapPointStruct[],
      conversions: ConversionStruct[],
      desired: DesiredStruct,
      receiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapAfterTransfer(
      provided: ProvidedStruct,
      swaps: SwapPointStruct[],
      conversions: ConversionStruct[],
      desired: DesiredStruct,
      receiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  estimateValue(
    assets: ProvidedStruct,
    inTermsOf: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  estimateValueERC20(
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    inTermsOf: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  estimateValueERC721(
    nft: AssetStruct,
    inTermsOf: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAmountsOut(
    provided: ProvidedStruct,
    desired: DesiredStruct,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber[],
      SwapPointStructOutput[],
      ConversionStructOutput[],
      BigNumber[]
    ] & {
      amounts: BigNumber[];
      swaps: SwapPointStructOutput[];
      conversions: ConversionStructOutput[];
      expectedUSDValues: BigNumber[];
    }
  >;

  getUnderlying(
    tokens: PromiseOrValue<string>[],
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<[string[], BigNumber[]]>;

  helper(overrides?: CallOverrides): Promise<string>;

  isSupported(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  networkToken(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  preSwapComputation(
    provided: ProvidedStruct,
    desired: DesiredStruct,
    overrides?: CallOverrides
  ): Promise<
    [SwapPointStructOutput[], ConversionStructOutput[]] & {
      swaps: SwapPointStructOutput[];
      conversions: ConversionStructOutput[];
    }
  >;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stableToken(overrides?: CallOverrides): Promise<string>;

  swap(
    provided: ProvidedStruct,
    swaps: SwapPointStruct[],
    conversions: ConversionStruct[],
    desired: DesiredStruct,
    receiver: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapAfterTransfer(
    provided: ProvidedStruct,
    swaps: SwapPointStruct[],
    conversions: ConversionStruct[],
    desired: DesiredStruct,
    receiver: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    estimateValue(
      assets: ProvidedStruct,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateValueERC20(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateValueERC721(
      nft: AssetStruct,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAmountsOut(
      provided: ProvidedStruct,
      desired: DesiredStruct,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber[],
        SwapPointStructOutput[],
        ConversionStructOutput[],
        BigNumber[]
      ] & {
        amounts: BigNumber[];
        swaps: SwapPointStructOutput[];
        conversions: ConversionStructOutput[];
        expectedUSDValues: BigNumber[];
      }
    >;

    getUnderlying(
      tokens: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber[]]>;

    helper(overrides?: CallOverrides): Promise<string>;

    isSupported(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    networkToken(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    preSwapComputation(
      provided: ProvidedStruct,
      desired: DesiredStruct,
      overrides?: CallOverrides
    ): Promise<
      [SwapPointStructOutput[], ConversionStructOutput[]] & {
        swaps: SwapPointStructOutput[];
        conversions: ConversionStructOutput[];
      }
    >;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    stableToken(overrides?: CallOverrides): Promise<string>;

    swap(
      provided: ProvidedStruct,
      swaps: SwapPointStruct[],
      conversions: ConversionStruct[],
      desired: DesiredStruct,
      receiver: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    swapAfterTransfer(
      provided: ProvidedStruct,
      swaps: SwapPointStruct[],
      conversions: ConversionStruct[],
      desired: DesiredStruct,
      receiver: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AssetsSent(address,address[],address[],uint256[])"(
      receiver?: null,
      tokens?: null,
      managers?: null,
      amountsAndIds?: null
    ): AssetsSentEventFilter;
    AssetsSent(
      receiver?: null,
      tokens?: null,
      managers?: null,
      amountsAndIds?: null
    ): AssetsSentEventFilter;

    "NFTMinted(address,uint256,address)"(
      manager?: null,
      tokenId?: null,
      pool?: null
    ): NFTMintedEventFilter;
    NFTMinted(
      manager?: null,
      tokenId?: null,
      pool?: null
    ): NFTMintedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    estimateValue(
      assets: ProvidedStruct,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateValueERC20(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimateValueERC721(
      nft: AssetStruct,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAmountsOut(
      provided: ProvidedStruct,
      desired: DesiredStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUnderlying(
      tokens: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    helper(overrides?: CallOverrides): Promise<BigNumber>;

    isSupported(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    networkToken(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    preSwapComputation(
      provided: ProvidedStruct,
      desired: DesiredStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stableToken(overrides?: CallOverrides): Promise<BigNumber>;

    swap(
      provided: ProvidedStruct,
      swaps: SwapPointStruct[],
      conversions: ConversionStruct[],
      desired: DesiredStruct,
      receiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapAfterTransfer(
      provided: ProvidedStruct,
      swaps: SwapPointStruct[],
      conversions: ConversionStruct[],
      desired: DesiredStruct,
      receiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    estimateValue(
      assets: ProvidedStruct,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    estimateValueERC20(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    estimateValueERC721(
      nft: AssetStruct,
      inTermsOf: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAmountsOut(
      provided: ProvidedStruct,
      desired: DesiredStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUnderlying(
      tokens: PromiseOrValue<string>[],
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    helper(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isSupported(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    networkToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    preSwapComputation(
      provided: ProvidedStruct,
      desired: DesiredStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stableToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swap(
      provided: ProvidedStruct,
      swaps: SwapPointStruct[],
      conversions: ConversionStruct[],
      desired: DesiredStruct,
      receiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapAfterTransfer(
      provided: ProvidedStruct,
      swaps: SwapPointStruct[],
      conversions: ConversionStruct[],
      desired: DesiredStruct,
      receiver: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
